[bind]
address=""
port=1337
[TLS]
tls=false
cert_path=""
key_path=""
[CORS]
enable=false
allow_origins=[]
allow_credentials=false
allow_methods=[]
allow_headers=[]
expose_headers=[]
max_age=0
[HTTP]
json_rpc_endpoint="/rpc"
[web_socket]
websocket_endpoint="/socketrpc"
max_websocket_sessions=50
read_buffer_size=4096
write_buffer_size=4096
[logging]
console_log_level="warn"
file_log_level="warn"
log_file=""
vm_log=false
[consensus]
tendermint_host="0.0.0.0:46657"
tmsp_listener="unix:///data/tendermint/app/app.sock"
